export const users = [
  {
    id: 1000,
    username: 'YEE',
    intraLogin: 'YEE_',
    image: '900674.jpg',
    rating: 1,
    wins: 10000,
    loses: 0,
  },
  {
    id: 1111,
    username: 'ann',
    intraLogin: 'ann_',
    image: '900674.jpg',
    rating: 3,
    wins: 500,
    loses: 40,

  },{
    id: 2222,
    username: 'oui',
    intraLogin: 'oui_',
  },
  {
    id: 3333,
    username: 'catMermaid',
    intraLogin: 'catMermaid_',
    image: '884014.png',
    rating: 4,
    wins: 26,
    loses: 20,
  },{
    id: 4444,
    username: 'sonic',
    intraLogin: 'sonic_',
    image: '884014.png',
    rating: 5,
    wins: 2,
    loses: 10,
  },
  {
    id: 5555,
    username: 'a',
    intraLogin: 'aa',
    // image: 'fuzzy',
    rating: 5,
    wins: 2,
    loses: 10,
  },{
    id: 6666,
    username: 'b',
    intraLogin: 'b',
    // image: 'fuzzy',
    rating: 5,
    wins: 2,
    loses: 10,
  },{
    id: 7777,
    username: 'c',
    intraLogin: 'c',
    // image: 'fuzzy',
    rating: 5,
    wins: 2,
    loses: 10,
  },{
    id: 8888,
    username: 'd',
    intraLogin: 'd',
    // image: 'fuzzy',
    rating: 5,
    wins: 2,
    loses: 10,
  },
  {
    id: 9999,
    username: 'e',
    intraLogin: 'e',
    // image: 'fuzzy',
    rating: 5,
    wins: 2,
    loses: 10,
  },
  {
    id: 1010,
    username: 'f',
    intraLogin: 'f',
    // image: 'fuzzy',
    rating: 5,
    wins: 2,
    loses: 10,
  },
];
